In [349]:
import os

In [350]:
train = open('ptb.train.txt', encoding='utf-8').read()
test = open('ptb.test.txt', encoding='utf-8').read()
valid = open('ptb.valid.txt', encoding='utf-8').read()

char_train = open('ptb.char.train.txt', encoding='utf-8').read()
char_test = open('ptb.char.test.txt', encoding='utf-8').read()
char_valid = open('ptb.char.valid.txt', encoding='utf-8').read()

In [255]:
print (len(set(train)))
print (len(set(test)))
print (len(set(valid)))
print (len(set(char_train)))
print (len(set(char_test)))
print (len(set(char_valid)))

50
48
50
51
49
51


In [161]:
print (len(set(train.split(' '))))
print (len(set(valid.split(' '))))
print (len(set(test.split(' '))))

10001
6023
6050


In [5]:
print (len(train.split(' ')))
print (len(valid.split(' ')))
print (len(test.split(' ')))

929590
73761
82431


In [27]:
char_train = open('ptb.char.train.txt', encoding='utf-8').read()
char_test = open('ptb.char.test.txt', encoding='utf-8').read()
char_valid = open('ptb.char.valid.txt', encoding='utf-8').read()

chars = char_valid.replace(' ', '')
d = open("ptb.char.valid.strip.txt", "w")
d.write(chars)

393042

In [162]:
chars = char_test.replace(' ','')

In [33]:
import torch
from torch.autograd import Variable
print(torch.__version__)

0.5.0a0+7450e91


In [34]:
a = torch.tensor([1,1])
b = Variable(a)

In [37]:
print (a.type())
print (b.type())

torch.LongTensor
torch.LongTensor


In [169]:
[i for i, c in enumerate(chars) if c == '.']


[1232,
 1716,
 2034,
 2546,
 2548,
 2868,
 5469,
 5471,
 5501,
 5503,
 5724,
 5966,
 6291,
 6293,
 6872,
 6996,
 7042,
 7313,
 7358,
 7682,
 7728,
 8914,
 9204,
 9414,
 9525,
 9828,
 10302,
 10413,
 10468,
 10470,
 10483,
 10746,
 10762,
 10841,
 10952,
 11011,
 11013,
 11110,
 11112,
 11149,
 11245,
 11247,
 11345,
 11347,
 11395,
 11517,
 11519,
 11714,
 11800,
 11802,
 11849,
 11862,
 11865,
 11867,
 12015,
 12017,
 12099,
 12179,
 12336,
 12338,
 13083,
 13085,
 13149,
 13281,
 13364,
 13473,
 13486,
 13568,
 13602,
 13654,
 13670,
 13736,
 13790,
 13902,
 13915,
 14142,
 14311,
 14487,
 14872,
 14895,
 14984,
 14986,
 15925,
 17052,
 17883,
 17906,
 18286,
 18329,
 19160,
 19187,
 19805,
 20250,
 20587,
 21217,
 21318,
 21820,
 22059,
 22311,
 22429,
 22888,
 22890,
 22907,
 23680,
 24058,
 24645,
 25470,
 25592,
 26067,
 26069,
 26111,
 26455,
 26476,
 26758,
 27415,
 27677,
 28017,
 28277,
 29214,
 29718,
 29779,
 29849,
 29851,
 29950,
 30418,
 30840,
 31129,
 31161,
 32010,
 3

In [171]:
def find_interval(array, idx):
    return a

In [256]:
from bisect import bisect_left
from bisect import bisect_right
from bisect import bisect


In [270]:
a = [2,10,15,23]
a = [0] + a

# not found
bisect_right
bisect_right + 1

# found


for i in range(0, 24):
    lead_marker_idx = max(0, bisect_left(a, i)-1)
    tail_marker_idx = max(0, bisect_right(a, i))
    
    if lead_marker_idx == tail_marker_idx:
        print (0)
    else:
        print (lead_marker_idx)
        
        
    

TypeError: unsupported operand type(s) for +: 'builtin_function_or_method' and 'int'

In [330]:
[1,2] + [3,4,5]

[1, 2, 3, 4, 5]

In [322]:
b = torch.Tensor(2,2,2)

In [335]:
print (b)
#print (b[:, 1, -1])
print (b[:, 1, :])

tensor([[[ 0.0000e+00,  4.6566e-10],
         [ 4.1856e+06, -3.6902e+19]],

        [[ 2.8026e-45,  4.6566e-10],
         [ 4.1805e+06,  1.8654e-40]]])
tensor([[ 4.1856e+06, -3.6902e+19],
        [ 4.1805e+06,  1.8654e-40]])


In [320]:
a = [2,10,15,23]
a = [-1] + a + [a[-1]+1]
t = 2

for i in range(0, 24):
    l = bisect_left(a, i)
    o = 1000
    if a[l] == i:
        o *= 1
    else:
        l1 = a[l - 1]
        l2 = a[l]
        o *= (i - l1) / (l2 - l1)
    print (o)


333.3333333333333
666.6666666666666
1000
125.0
250.0
375.0
500.0
625.0
750.0
875.0
1000
200.0
400.0
600.0
800.0
1000
125.0
250.0
375.0
500.0
625.0
750.0
875.0
1000


In [352]:
import torch
torch.Tensor([23]) / 100

tensor([ 0.2300])

In [356]:
aa = {'a':'b'}

In [363]:
a = [1,2,3,4]

In [371]:
a = torch.Tensor([11,23,34,4])
values, indices = a.min(0)
print (i, k)

tensor(4.) tensor(3)
